Sequential 클래스 이용

In [2]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Input,Dense

model = Sequential()
model.add(Input(shape=(4,)))
model.add(Dense(50,activation='relu'))
model.add(Dense(3,activation='softmax'))
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 50)             │           250 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 3)              │           153 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 403 (1.57 KB)

 Trainable params: 403 (1.57 KB)

 Non-trainable params: 0 (0.00 B)

함수형 API 이용

In [3]:
from tensorflow.keras import Model
from tensorflow.keras.layers import Input,Dense
from tensorflow.keras.layers import concatenate,Activation

input = Input(shape=(4,))
dense1 = Dense(50,activation='relu')(input)
dense2 = Dense(80,activation='relu')(input)
dense3 = Dense(30,activation='relu')(input)
x = concatenate([dense1,dense2,dense3])
output = Dense(3,activation='softmax')(x)
model = Model(inputs=input,outputs=output)
model.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_1       │ (None, 4)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_2 (Dense)     │ (None, 50)        │        250 │ input_layer_1[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_3 (Dense)     │ (None, 80)        │        400 │ input_layer_1[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_4 (Dense)     │ (None, 30)        │        150 │ input_layer_1[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate         │ (None, 160)       │          0 │ dense_2[0][0],    │
│ (Concatenate)       │                   │            │ dense_3[0][0],    │
│                     │                   │            │ dense_4[0][0]     │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_5 (Dense)     │ (None, 3)         │        483 │ concatenate[0][0] │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 1,283 (5.01 KB)

 Trainable params: 1,283 (5.01 KB)

 Non-trainable params: 0 (0.00 B)

In [4]:
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Input

model = Sequential()
model.add(Input(shape=(4,)))
model.add(Dense(100, activation="relu"))
model.add(Dense(300, activation="relu"))
model.add(Dense(3, activation="softmax"))
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_6 (Dense)                 │ (None, 100)            │           500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 300)            │        30,300 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 3)              │           903 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 31,703 (123.84 KB)

 Trainable params: 31,703 (123.84 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model4 = Sequential()
model4.add(Dense(3, activation='softmax', input_shape=(4,)))
model4.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])


/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [5]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',metrics=['accuracy'])

In [ ]:
model4.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',metrics=['accuracy'])

In [7]:
from sklearn import datasets
iris = datasets.load_iris()
X, y = iris.data,iris.target

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [8]:
model.fit(X_train,y_train,epochs=200)

Epoch 1/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 18ms/step - accuracy: 0.1938 - loss: 1.0725  
Epoch 2/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6379 - loss: 0.8748 
Epoch 3/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7073 - loss: 0.7092
Epoch 4/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9060 - loss: 0.6271
Epoch 5/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9421 - loss: 0.5266
Epoch 6/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.7024 - loss: 0.4866
Epoch 7/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9324 - loss: 0.4169
Epoch 8/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9216 - loss: 0.3898
Epoch 9/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step - accuracy: 0.9431 - loss: 0.3501
Epoch 10/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step - accuracy: 0.8938 - loss: 0.3080
Epoch 11/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step - accuracy: 0.9372 - loss: 0.3012
Epoch 12/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9598 -

In [ ]:
model4.fit(X_train,y_train,epochs=200)

Epoch 1/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 10ms/step - accuracy: 0.3795 - loss: 2.2585 
Epoch 2/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3305 - loss: 2.3409
Epoch 3/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3628 - loss: 2.2837
Epoch 4/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3389 - loss: 2.2876
Epoch 5/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3639 - loss: 2.2376
Epoch 6/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3795 - loss: 2.1015 
Epoch 7/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3545 - loss: 2.1075 
Epoch 8/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3389 - loss: 2.0828 
Epoch 9/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3441 - loss: 2.1558
Epoch 10/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3566 - loss: 2.0966
Epoch 11/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3326 - loss: 2.0612
Epoch 12/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.3462 - lo

In [9]:
model.evaluate(X_test,y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - accuracy: 1.0000 - loss: 0.0330 


[0.03061203472316265, 1.0]

In [ ]:
model4.evaluate(X_test,y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step - accuracy: 0.5875 - loss: 0.7736 


[0.7680186033248901, 0.6000000238418579]

In [10]:
from tensorflow.keras import Sequential, layers

In [ ]:
model = Sequential()
model.add(layers.Input(shape=(4,)))
model.add(layers.Dense(5,activation='relu'))
model.add(layers.Dense(6,activation='relu'))
model.add(layers.Dense(3,activation='softmax'))
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_9 (Dense)                 │ (None, 5)              │            25 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_10 (Dense)                │ (None, 6)              │            36 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_11 (Dense)                │ (None, 3)              │            21 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 82 (328.00 B)

 Trainable params: 82 (328.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',metrics=['accuracy'])

In [ ]:
model.fit(X_train,y_train,epochs=20)

Epoch 1/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 11ms/step - accuracy: 0.3552 - loss: 1.1053
Epoch 2/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4020 - loss: 1.1089
Epoch 3/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5970 - loss: 1.0796
Epoch 4/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6389 - loss: 1.0725
Epoch 5/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6250 - loss: 1.0770
Epoch 6/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6479 - loss: 1.0603 
Epoch 7/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7032 - loss: 1.0345 
Epoch 8/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6695 - loss: 1.0377
Epoch 9/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6528 - loss: 1.0335
Epoch 10/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6288 - loss: 1.0280
Epoch 11/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6507 - loss: 1.0157
Epoch 12/20
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6570 - loss: 1.0022
E

In [ ]:
model.evaluate(X_test,y_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step - accuracy: 0.7093 - loss: 0.9204 


[0.9243506789207458, 0.6888889074325562]

모델의 저장 및 예측

In [11]:
# 모델 저장
model.save("my_model.keras")
print("Model has saved")

Model has saved


In [13]:
import numpy as np
from tensorflow.keras.models import load_model

# load saved model
loaded_model = load_model("my_model.keras")
print("model succesfully loaded")

# insert new data (iris has 4 feature)
X_new = np.array([4.6,3.6,1.0,0.2]).reshape(1,-1) # (1,4) shape change

# predict
predictions = loaded_model.predict(X_new)
# predict result
print("예측된 확률분호:",predictions)
print("예측된 클래스:",np.argmax(predictions))

model succesfully loaded
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step
예측된 확률분호: [[9.9999964e-01 4.0820174e-07 9.4469273e-14]]
예측된 클래스: 0


reshape(1, -1)
딥러닝 모델 입력 요구사항
TensorFlow/Keras의 신경망은 입력 데이터를 2D 배열(배치 크기, 특성 수) 형태로 받음.
즉, (batch_size, feature_dim) 형태가 필요함.
reshape(1, -1)을 통해 (1, 4)로 변환하면 배치 크기가 1인 샘플로 인식됨.
배치 처리(batch processing)
모델은 한 번에 여러 개의 샘플(batch)을 받을 수 있음.
예를 들어, reshape(3, -1)이라면 3개의 샘플을 동시에 예측


In [14]:
X_new = np.array([[4.6, 3.6, 1.0, 0.2],
                  [5.0, 3.4, 1.2, 0.3],
                  [4.8, 3.1, 1.3, 0.2]]).reshape(3, -1)
print(X_new.shape)
# 출력: (3, 4)

(3, 4)


Vs. reshape(-1, 4)와의 차이점
reshape(1, -1) : 배치 크기 1인 샘플 → (1, 4)
reshape(-1, 4) : 자동으로 샘플 개수를 맞춤 → N개의 샘플을 가진 (N, 4) 형태
-1은 자동으로 샘플 개수를 결정함.

In [16]:
from types import prepare_class
import numpy as np
from tensorflow.keras.models import load_model

loaded_model = load_model("my_model.keras")
print("model loaded")
X_new = np.array([
[5.1, 3.5, 1.4, 0.2],
[6.3, 2.8, 5.1, 1.5],
[6.5, 3.0, 5.5, 1.8]
])

print("input data shape",X_new) #(3,4)
predictions = loaded_model.predict(X_new)
print("예측된 확률분포:\n",predictions)
prepare_classes = np.argmax(predictions,axis=1)
print("predeicted class",prepare_classes)

model loaded
input data shape [[5.1 3.5 1.4 0.2]
 [6.3 2.8 5.1 1.5]
 [6.5 3.  5.5 1.8]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 165ms/step
예측된 확률분포:
 [[9.9999762e-01 2.4033300e-06 4.0496973e-13]
 [3.8840655e-05 3.5155380e-01 6.4840734e-01]
 [1.9247743e-06 2.1217955e-02 9.7878015e-01]]
predeicted class [0 2 2]


In [22]:
from tensorflow.keras import Model
from tensorflow.keras.layers import Input,Dense
from tensorflow.keras.layers import concatenate,Activation

input = Input(shape=(4,))
dense1 = Dense(30,activation='relu')(input)
dense2 = Dense(20,activation='relu')(input)
dense3 = Dense(10,activation='relu')(input)
x = concatenate([dense1,dense2,dense3])
output = Dense(3,activation='softmax')(x)
model = Model(inputs=input,outputs=output)
model.summary()

Model: "functional_19"

┏━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Layer (type)        ┃ Output Shape      ┃    Param # ┃ Connected to      ┃
┡━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│ input_layer_4       │ (None, 4)         │          0 │ -                 │
│ (InputLayer)        │                   │            │                   │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_13 (Dense)    │ (None, 30)        │        150 │ input_layer_4[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_14 (Dense)    │ (None, 20)        │        100 │ input_layer_4[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_15 (Dense)    │ (None, 10)        │         50 │ input_layer_4[0]… │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ concatenate_2       │ (None, 60)        │          0 │ dense_13[0][0],   │
│ (Concatenate)       │                   │            │ dense_14[0][0],   │
│                     │                   │            │ dense_15[0][0]    │
├─────────────────────┼───────────────────┼────────────┼───────────────────┤
│ dense_16 (Dense)    │ (None, 3)         │        183 │ concatenate_2[0]… │
└─────────────────────┴───────────────────┴────────────┴───────────────────┘

 Total params: 483 (1.89 KB)

 Trainable params: 483 (1.89 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.compile(loss='sparse_categorical_crossentropy',
              optimizer='adam',metrics=['accuracy'])

In [ ]:
from sklearn import datasets
iris = datasets.load_iris()
X, y = iris.data,iris.target

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=1)

In [24]:
model.fit(X_train,y_train,epochs=200)

Epoch 1/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 10ms/step - accuracy: 0.3125 - loss: 2.4677
Epoch 2/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.2969 - loss: 2.0001
Epoch 3/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4862 - loss: 1.8616
Epoch 4/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6590 - loss: 1.5408 
Epoch 5/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6559 - loss: 1.3533
Epoch 6/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6625 - loss: 1.2126
Epoch 7/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.6671 - loss: 1.0902
Epoch 8/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.5054 - loss: 1.0779
Epoch 9/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3088 - loss: 1.0148 
Epoch 10/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3285 - loss: 0.9730
Epoch 11/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3632 - loss: 0.9553
Epoch 12/200
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.3368 - 

In [26]:
# 모델 저장
model.save("my_model.keras")
print("Model has saved")

Model has saved


In [27]:
import numpy as np


X_new = np.array([
    [5.1, 3.5, 1.4, 0.2],
    [4.9, 3.0, 1.4, 0.2],
    [6.3, 3.3, 4.7, 1.6],
    [5.8, 2.7, 4.1, 1.0],
    [7.1, 3.0, 5.9, 2.1],
    [6.5, 3.0, 5.2, 2.0],
    [5.0, 3.4, 1.6, 0.4],
    [6.1, 2.9, 4.7, 1.4],
    [6.7, 3.1, 5.6, 2.4],
    [5.4, 3.9, 1.7, 0.4]
])

from types import prepare_class
import numpy as np
from tensorflow.keras.models import load_model

loaded_model = load_model("my_model.keras")
print("model loaded")


print("input data shape",X_new) #(3,4)
predictions = loaded_model.predict(X_new)
print("예측된 확률분포:\n",predictions)
prepare_classes = np.argmax(predictions,axis=1)
print("predeicted class",prepare_classes)


model loaded
input data shape [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [6.3 3.3 4.7 1.6]
 [5.8 2.7 4.1 1. ]
 [7.1 3.  5.9 2.1]
 [6.5 3.  5.2 2. ]
 [5.  3.4 1.6 0.4]
 [6.1 2.9 4.7 1.4]
 [6.7 3.1 5.6 2.4]
 [5.4 3.9 1.7 0.4]]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step
예측된 확률분포:
 [[9.8404551e-01 1.5951339e-02 3.1688610e-06]
 [9.7046995e-01 2.9519759e-02 1.0350908e-05]
 [6.6274954e-03 6.9583249e-01 2.9754004e-01]
 [2.0982129e-02 8.7669259e-01 1.0232522e-01]
 [5.7423251e-05 1.7575116e-01 8.2419133e-01]
 [4.3896592e-04 3.0185124e-01 6.9770974e-01]
 [9.7100669e-01 2.8980596e-02 1.2705850e-05]
 [3.8357018e-03 6.5095776e-01 3.4520653e-01]
 [5.3082626e-05 1.0886745e-01 8.9107949e-01]
 [9.8380846e-01 1.6188107e-02 3.3932793e-06]]
predeicted class [0 0 1 1 2 2 0 1 2 0]
